### ISSUE TITLE
Course Section Protection

### ISSUE THREAD

**Issue by VOOM108** [moodleuulm/moodle-availability_password#5] opened 2018-03-16 13:22 UTC
Course Section Protection would be greatly appreciated!

**Comment by abias** [comment] 2018-03-16 15:53
Hi VOOM108,

you are the first one to request course section protection since we wrote and published this plugin in early 2016 and added the section https://github.com/moodleuulm/moodle-availability_password#protection-course-sections to the README file.

Currently, we don't have any local need and resources to implement this addition. I will keep this ticket open for a while to give others the chance to chime in, but in the end course section protection probably can only become true if anyone from the community will code it and submit a pull request.

Thanks,
Alex

**Comment by VOOM108** [comment] 2018-03-16 16:03
I see, thank you :) I found a workaround, that might help: I create a lesson with only one question, answertype "shortinput" - the right answer is the password. Retries can be configured, the right password rewards with the points for the lesson. The section uses a condition with this lesson needing to be closed with the resp. points awarded. 

This is nice since the lesson for the third section can be included in the second section so no one can try to open all sessions but it is only possible one by one in the right order ;) 

One thing I noticed about the plugin: I tried to password-protect a folder with the documents instead of putting them into sections - but putting in the password for the folder resulted in an error-message. It still opened the folder-resource, but it looked odd. Anyway, since documents in folders can only be downloaded, this was not really an option for us. Thus the solution pointed out above :)

**Comment by abias** [comment] 2018-03-29 12:56
Hi VOOM108,

> I found a workaround, that might help: [...]

I am unsure if this workaround is really straightforward, but thanks for documenting it 👍 

> One thing I noticed about the plugin: I tried to password-protect a folder with the documents instead of putting them into sections - but putting in the password for the folder resulted in an error-message. It still opened the folder-resource, but it looked odd. Anyway, since documents in folders can only be downloaded, this was not really an option for us. Thus the solution pointed out above :)

Would you mind creating a new issue for this problem and adding a screenshot / steps to reproduce for it?

Thanks,
Alex

**Comment by VOOM108** [comment] 2018-03-29 13:10
> I am unsure if this workaround is really straightforward,

I's surely not, but so far the only way I found, and it does not even look odd for the user. ;) 

> Would you mind creating a new issue for this problem and adding a screenshot / steps to reproduce for it?

Sure, will do, but will have to reproduce it first, so give me some time... :)

**Comment by VOOM108** [comment] 2018-03-29 16:13
I could not reproduce the error anymore! Seems there has been a specific or temporary "hickup"... :)

**Comment by abias** [comment] 2018-03-29 19:18
> I could not reproduce the error anymore! Seems there has been a specific or temporary "hickup"... :)

This is good news - somehow. Don't hesitate to come back if you encounter the problem once again.

**Comment by abias** [comment] 2020-02-13 06:53
This issue is now nearly 2 years old and during this time neither in our institution nor in the community the need to have course section protection has arisen once more.

Thus, I dare to close this issue for now.

**Closed as completed by abias** 2020-02-13 06:53 UTC
